import type { Metadata } from "next";
import localFont from "next/font/local";
import "@repo/ui/styles/globals.css";
import { SidebarInset, SidebarTrigger } from "@repo/ui/components/sidebar";
import { AppSidebar } from "@repo/ui/components/app/AppSidebar";
import { SharedProvider } from "@repo/ui/components/app/SharedProvider";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <SharedProvider>
          <AppSidebar softNav={["/", "calendar", "search", "settings"]} />
          <div className="flex flex-col">
            <SidebarTrigger />
            <SidebarInset>{children}</SidebarInset>
          </div>
        </SharedProvider>
      </body>
    </html>
  );
}
